In [2]:
import numpy as np
import pandas as pd
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split

In [3]:
iris_data = load_iris()

df = pd.DataFrame(data=iris_data.data, columns=iris_data.feature_names)
df.head(5)

   sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                5.1               3.5                1.4               0.2
1                4.9               3.0                1.4               0.2
2                4.7               3.2                1.3               0.2
3                4.6               3.1                1.5               0.2
4                5.0               3.6                1.4               0.2

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 4 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   sepal length (cm)  150 non-null    float64
 1   sepal width (cm)   150 non-null    float64
 2   petal length (cm)  150 non-null    float64
 3   petal width (cm)   150 non-null    float64
dtypes: float64(4)
memory usage: 4.8 KB

In [5]:
df.describe()

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm)
count,150.000000,150.000000,150.000000,150.000000
mean,5.843333,3.057333,3.758000,1.199333
std,0.828066,0.435866,1.765298,0.762238
min,4.300000,2.000000,1.000000,0.100000
25%,5.100000,2.800000,1.600000,0.300000
50%,5.800000,3.000000,4.350000,1.300000
75%,6.400000,3.300000,5.100000,1.800000
max,7.900000,4.400000,6.900000,2.500000

In [6]:
# Processing
# 1. check outlier
Q1 = df.quantile(0.25)
Q3 = df.quantile(0.75)
IQR = Q3-Q1
upper_bound = Q1-1.5*IQR
lower_bound = Q3+1.5*IQR
upper_bound, lower_bound

(sepal length (cm)    3.15
 sepal width (cm)     2.05
 petal length (cm)   -3.65
 petal width (cm)    -1.95
 dtype: float64,
 sepal length (cm)     8.35
 sepal width (cm)      4.05
 petal length (cm)    10.35
 petal width (cm)      4.05
 dtype: float64)

In [7]:
#2. Stardardized
u = df.mean()
ơ = df.std()
X = (df-u)/ơ
X.describe()

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm)
count,1.500000e+02,1.500000e+02,1.500000e+02,1.500000e+02
mean,-1.515825e-15,-1.894781e-15,-1.515825e-15,-8.526513e-16
std,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00
min,-1.863780e+00,-2.425820e+00,-1.562342e+00,-1.442245e+00
25%,-8.976739e-01,-5.903951e-01,-1.222456e+00,-1.179859e+00
50%,-5.233076e-02,-1.315388e-01,3.353541e-01,1.320673e-01
75%,6.722490e-01,5.567457e-01,7.602115e-01,7.880307e-01
max,2.483699e+00,3.080455e+00,1.779869e+00,1.706379e+00

In [8]:
# Chia train, test
y = iris_data.target
y = pd.Series(iris_data.target) # .target là kiểu numpy
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)
X_train, y_train

(     sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
 8            -1.743017         -0.360967          -1.335752         -1.311052
 106          -1.139200         -1.278680           0.420326          0.656838
 76            1.155302         -0.590395           0.590269          0.263260
 9            -1.139200          0.097889          -1.279104         -1.442245
 89           -0.414621         -1.278680           0.137087          0.132067
 ..                 ...               ...                ...               ...
 37           -1.139200          1.245030          -1.335752         -1.442245
 2            -1.380727          0.327318          -1.392399         -1.311052
 33           -0.414621          2.621599          -1.335752         -1.311052
 52            1.276066          0.097889           0.646916          0.394453
 3            -1.501490          0.097889          -1.279104         -1.311052

 [120 rows x 4 columns],
 8      0
 106    2
 76     1
 9      0
 89     1
       ..
 37     0
 2      0
 33     0
 52     1
 3      0
 Length: 120, dtype: int64)

In [9]:
# DO 3 id của 3 tham số là khác nhau dẫn đến việc truy cập dữ liệu bị lỗi
#  nên reset index để truy cập đúng
_X_train = X_train.reset_index(drop=True)
_y_train = y_train.reset_index(drop=True)
_X_test = X_test.reset_index(drop=True)
_y_test = y_test.reset_index(drop=True)

In [17]:
_X_train - y_train

,0,1,2,3,4,5,6,8,9,11,...,143,144,145,146,148,149,petal length (cm),petal width (cm),sepal length (cm),sepal width (cm)
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
115,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
116,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
117,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
118,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
119,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [11]:
def KNN_model(_X_train, _X_test, _y_train, K):
    l_labels=[]
    for i in range(0, len(_X_test)):
        # Thực hiện trước khi chạy vòng lặp
        distance = np.sqrt(((_X_train - _X_test.iloc[i])**2)).sum(axis=1)
        # Lấy top K nhỏ nhất
        topK = distance.sort_values().head(K)
        # Vote
        vote = _y_train.iloc[topK.index].mode()[0]
        l_labels.append(vote)
    return l_labels

In [12]:
K=3
knn = KNN_model(_X_train, _X_test, _y_train, K)

In [13]:
# Đánh giá mô hình
# Cách 1: Dùng vòng lặp + if else
TP = 0
FN = 0
FP = 0
TN = 0
for i in range(0, len(_X_test)):
    if knn[i] == 0 and _y_test.iloc[i] == 0:
        TP = TP + 1
    elif knn[i] == 0 and _y_test.iloc[i] != 0:
        FN = FN + 1
    elif knn[i] != 0 and _y_test.iloc[i] == 0:
        FP = FP + 1
    elif knn[i] != 0 and _y_test.iloc[i] != 0:
        TN = TN + 1
print("TP: ", TP)
print("FN: ", FN)
print("FP: ", FP)
print("TN: ", TN)
accuracy = (TP+TN)/(TP+TN+FP+FN)
print("Accuracy: ", accuracy)

TP:  10
FN:  0
FP:  0
TN:  20
Accuracy:  1.0

In [14]:
# Cách 2: Dùng matrix
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(_y_test, knn)
print(cm)   
accuracy = (cm[0][0]+cm[1][1]+cm[2][2])/cm.sum()
print("Accuracy: ", accuracy)

[[10  0  0]
 [ 0 10  0]
 [ 0  1  9]]
Accuracy:  0.9666666666666667